name: Get Changed Folder

on:
  push:
    branches:
      - ItzhakBokris/changes-script

jobs:
  get_changed_folder:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ItzhakBokris/changes-script

      - name: Find changed folder
        id: find_changed_folder
        run: |
          # Use git to get the list of changed files
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          # Initialize an empty array to store unique directory names
          changed_folders=()
  
          # Loop through the changed files to find the folders
          for file in $changed_files; do
            # Extract the folder path
            folder=$(dirname "$file")

            # Get the first part of the directory path (the first folder)
            base_folder=$(echo "$folder" | cut -d'/' -f2)
          
            # Check if the file being processed is the workflow YAML file, and skip it
            if [[ "$base_folder" == ".github" ]]; then
              continue
            fi
          
            echo $base_folder
          
            # Add the directory to the array if it's not already in the array
            if [[ ! " ${changed_folders[@]} " =~ " ${base_folder} " ]]; then
              changed_folders+=("$base_folder")
            fi
          done
          
          # Set the output variable with the list of changed folders
          echo "::set-output name=changed_folders::${changed_folders[*]}"

      - name: Use the changed folder
        run: |
          # Access the changed folder from the previous step's output
          changed_folders="${{ steps.find_changed_folder.outputs.changed_folders }}"
          echo "Changed folders is: $changed_folders"
