name: Get Changed Folder

on:
  push:
    branches:
      - ItzhakBokris/changes-script

jobs:
  get_changed_folder:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ItzhakBokris/changes-script

      - name: Find changed folder
        id: find_changed_folder
        run: |
          # Use git to get the list of changed files
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          
          echo 111
          echo $changed_files
          
          # Initialize an empty array to store unique directory names
          changed_folders=()
  
          # Loop through the changed files to find the folders
          for file in $changed_files; do
            # Extract the folder path
            folder=$(dirname "$file")
          
            echo 2222
            echo $folder
          
            # Get the last part of the parent directory path (the immediate ancestor folder)
            immediate_ancestor=$(basename "$folder")
          
            echo 333
            echo $immediate_ancestor
          
            # Add the directory to the array if it's not already in the array
            if [[ ! " ${changed_folders[@]} " =~ " ${immediate_ancestor} " ]]; then
              changed_folders+=("$immediate_ancestor")
          
              echo 4444
              echo $changed_folders
            fi
          done
          
          # Set the output variable with the list of changed folders
          echo "::set-output name=changed_folders::${changed_folders[*]}"

      - name: Use the changed folder
        run: |
          # Access the changed folder from the previous step's output
          changed_folders="${{ steps.find_changed_folder.outputs.changed_folders }}"
          echo "Changed folders is: $changed_folders"
